# Generated by Django 4.0 on 2024-10-12 10:12

import core.models
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Biz Kimik',
                'verbose_name_plural': 'Biz Kimik',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image', models.ImageField(upload_to=core.models.get_image_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_thumbnail)),
                ('author', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_model', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Manşet',
                'verbose_name_plural': 'Manşet',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image', models.ImageField(upload_to=core.models.get_image_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path)),
                ('author', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(db_index=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Müsahibə',
                'verbose_name_plural': 'Müsahibə',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(db_index=True)),
                ('image', models.ImageField(upload_to=core.models.get_image_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path)),
                ('author', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yeniliklər',
                'verbose_name_plural': 'Yeniliklər',
            },
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image', models.ImageField(upload_to=core.models.get_image_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path)),
                ('author', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(db_index=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Poeziya',
                'verbose_name_plural': 'Poeziya',
            },
        ),
        migrations.CreateModel(
            name='Prose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(db_index=True)),
                ('image', models.ImageField(upload_to=core.models.get_image_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path)),
                ('author', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nəsr',
                'verbose_name_plural': 'Nəsr',
            },
        ),
        migrations.CreateModel(
            name='SubmissionGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Yazı Qəbulu',
                'verbose_name_plural': 'Yazı Qəbulu',
            },
        ),
        migrations.CreateModel(
            name='Writings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(db_index=True)),
                ('image', models.ImageField(upload_to=core.models.get_image_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path)),
                ('author', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yazılar',
                'verbose_name_plural': 'Yazılar',
            },
        ),
    ]
