# Generated by Django 4.0 on 2024-10-12 18:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
        migrations.AlterField(
            model_name='home',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to=core.models.get_image_upload_thumbnail),
            preserve_default=False,
        ),
    ]
