# Generated by Django 4.0 on 2024-10-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_home_image_alter_home_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='content',
        ),
    ]
