# Generated by Django 4.0 on 2024-10-16 12:31

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_aboutus_content_remove_aboutus_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealReaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Oxuculara müraciət',
                'verbose_name_plural': 'Oxuculara müraciət',
            },
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-created_at'], 'verbose_name': 'Manşet', 'verbose_name_plural': 'Manşet'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Müsahibə', 'verbose_name_plural': 'Müsahibə'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yeniliklər', 'verbose_name_plural': 'Yeniliklər'},
        ),
        migrations.AlterModelOptions(
            name='poetry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Poeziya', 'verbose_name_plural': 'Poeziya'},
        ),
        migrations.AlterModelOptions(
            name='prose',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nəsr', 'verbose_name_plural': 'Nəsr'},
        ),
        migrations.AlterModelOptions(
            name='writings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yazılar', 'verbose_name_plural': 'Yazılar'},
        ),
    ]
