# Generated by Django 4.0 on 2024-09-29 19:20

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_interview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Müsahibə', 'verbose_name_plural': 'Müsahibə'},
        ),
        migrations.AlterField(
            model_name='interview',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
