# Generated by Django 4.0 on 2024-10-13 18:05

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_home_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(db_index=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='prose',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(db_index=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='writings',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(db_index=True, verbose_name='Text'),
        ),
    ]
