# Generated by Django 4.0 on 2024-10-13 18:32

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_news_content_alter_prose_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionguidelines',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
