# Generated by Django 4.0 on 2024-10-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Manşet', 'verbose_name_plural': 'Manşet'},
        ),
        migrations.AddField(
            model_name='home',
            name='source_model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
