# Generated by Django 4.0 on 2024-10-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_interview_content_alter_news_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='interview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='poetry',
            name='author',
        ),
        migrations.RemoveField(
            model_name='prose',
            name='author',
        ),
        migrations.RemoveField(
            model_name='writings',
            name='author',
        ),
        migrations.AddField(
            model_name='interview',
            name='authors',
            field=models.ManyToManyField(related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AddField(
            model_name='news',
            name='authors',
            field=models.ManyToManyField(related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AddField(
            model_name='poetry',
            name='authors',
            field=models.ManyToManyField(related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AddField(
            model_name='prose',
            name='authors',
            field=models.ManyToManyField(related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AddField(
            model_name='writings',
            name='authors',
            field=models.ManyToManyField(related_name='%(class)s_authors', to='core.Author'),
        ),
    ]
