# Generated by Django 4.0 on 2024-10-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_home_options_home_source_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writtings',
            new_name='Writings',
        ),
    ]
