# Generated by Django 4.0 on 2024-10-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_author_remove_interview_author_remove_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='authors',
            field=models.ManyToManyField(null=True, related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='authors',
            field=models.ManyToManyField(null=True, related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='authors',
            field=models.ManyToManyField(null=True, related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='prose',
            name='authors',
            field=models.ManyToManyField(null=True, related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='writings',
            name='authors',
            field=models.ManyToManyField(null=True, related_name='%(class)s_authors', to='core.Author'),
        ),
    ]
