# Generated by Django 4.0 on 2024-10-06 18:41

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'Yazı Qəbulu',
                'verbose_name_plural': 'Yazı Qəbulu',
            },
        ),
    ]
