# Generated by Django 4.0 on 2024-10-06 21:09

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_submissionguidelines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='author',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(db_index=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='author',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(db_index=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prose',
            name='author',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prose',
            name='content',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='prose',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='writings',
            name='author',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='writings',
            name='content',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='writings',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['title', 'author'], name='core_interv_title_5cf735_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['title', 'author'], name='core_news_title_d9783a_idx'),
        ),
        migrations.AddIndex(
            model_name='poetry',
            index=models.Index(fields=['title', 'author'], name='core_poetry_title_bf483c_idx'),
        ),
        migrations.AddIndex(
            model_name='prose',
            index=models.Index(fields=['title', 'author'], name='core_prose_title_253236_idx'),
        ),
        migrations.AddIndex(
            model_name='writings',
            index=models.Index(fields=['title', 'author'], name='core_writin_title_f081bc_idx'),
        ),
    ]
