# Generated by Django 4.0 on 2024-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_interview_authors_alter_news_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='author',
        ),
        migrations.AddField(
            model_name='home',
            name='authors',
            field=models.ManyToManyField(blank=True, to='core.Author'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='prose',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='writings',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_authors', to='core.Author'),
        ),
    ]
