# Generated by Django 4.0 on 2024-10-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_interview_author_alter_interview_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='poetry',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='prose',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='writings',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
