# Generated by Django 4.0 on 2024-10-10 17:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_interview_core_interv_title_5cf735_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='prose',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='writings',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_image_upload_path),
        ),
    ]
